# Generated by Django 5.2.16 on 2026-07-22 18:57

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPurgeState',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_deleted_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('expires_at', models.DateTimeField(db_default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(days=90))), editable=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_inbox_idx'), models.Index(fields=['expires_at', 'id'], name='notif_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='notifications_unique_recipient_event')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION notifications_set_expiry() RETURNS trigger AS $$
                BEGIN
                    NEW.created_at := CURRENT_TIMESTAMP;
                    NEW.expires_at := NEW.created_at + INTERVAL '90 days';
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER notifications_expiry_authority
                BEFORE INSERT ON notifications_notification
                FOR EACH ROW EXECUTE FUNCTION notifications_set_expiry();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS notifications_expiry_authority
                    ON notifications_notification;
                DROP FUNCTION IF EXISTS notifications_set_expiry();
            """,
        ),
    ]
