# Generated by Django 5.2.16 on 2026-07-22 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


HISTORY_IMMUTABLE_SQL = """
CREATE OR REPLACE FUNCTION trades_reject_history_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'trade status history is immutable';
END;
$$;
CREATE TRIGGER trades_status_history_immutable
BEFORE UPDATE OR DELETE ON trades_tradestatushistory
FOR EACH ROW EXECUTE FUNCTION trades_reject_history_mutation();
"""

HISTORY_IMMUTABLE_REVERSE_SQL = """
DROP TRIGGER IF EXISTS trades_status_history_immutable ON trades_tradestatushistory;
DROP FUNCTION IF EXISTS trades_reject_history_mutation();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_typed_trade_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TradeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('RESERVED', '예약 중'), ('CANCELLED', '예약 취소'), ('COMPLETED', '거래 완료')], max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='trades.trade')),
            ],
            options={
                'ordering': ('trade_id', 'version'),
                'constraints': [models.UniqueConstraint(fields=('trade', 'version'), name='trades_history_trade_version_unique')],
            },
        ),
        migrations.RunSQL(
            sql=HISTORY_IMMUTABLE_SQL,
            reverse_sql=HISTORY_IMMUTABLE_REVERSE_SQL,
        ),
    ]
