# Generated by Django 5.2.16 on 2026-07-22 18:56

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_version_tradestatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_reviews', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='trades.trade')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ReviewVisibilityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('HIDE', 'Hide'), ('RESTORE', 'Restore')], max_length=8)),
                ('reason', models.TextField(max_length=500)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_visibility_actions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visibility_actions', to='trades.review')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('trade', 'author'), name='trades_review_direction_unique'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('author', models.F('subject')), _negated=True), name='trades_review_distinct_parties'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='trades_review_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='trades_review_body_required'),
        ),
        migrations.AddConstraint(
            model_name='reviewvisibilityaction',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='trades_review_visibility_reason_required'),
        ),
    ]
