# Generated by Django 5.2.16 on 2026-07-22 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


def bootstrap_existing_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    MockAccount = apps.get_model("transfers", "MockAccount")
    LedgerAccount = apps.get_model("transfers", "LedgerAccount")
    LedgerJournal = apps.get_model("transfers", "LedgerJournal")
    LedgerEntry = apps.get_model("transfers", "LedgerEntry")
    TransferSafetyState = apps.get_model("transfers", "TransferSafetyState")
    reserve, _ = LedgerAccount.objects.get_or_create(
        code="SEED_RESERVE",
        defaults={"kind": "SYSTEM_ISSUANCE"},
    )
    for user_id in User.objects.order_by("pk").values_list("pk", flat=True):
        account, created = MockAccount.objects.get_or_create(
            user_id=user_id,
            defaults={"balance": Decimal("100000.00")},
        )
        if not created:
            continue
        ledger = LedgerAccount.objects.create(
            kind="USER",
            mock_account=account,
            code=f"USER:{user_id}",
        )
        journal = LedgerJournal.objects.create(
            kind="SEED_ISSUE",
            target_mock_account=account,
        )
        LedgerEntry.objects.bulk_create(
            (
                LedgerEntry(journal=journal, account=ledger, amount=Decimal("100000.00")),
                LedgerEntry(journal=journal, account=reserve, amount=Decimal("-100000.00")),
            )
        )
    TransferSafetyState.objects.get_or_create(singleton=1)


LEDGER_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION transfers_reject_ledger_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'ledger journals and entries are immutable';
END;
$$;

CREATE OR REPLACE FUNCTION transfers_validate_balanced_journal()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    checked_journal uuid;
    entry_count bigint;
    entry_total numeric;
BEGIN
    checked_journal := COALESCE(
        (to_jsonb(NEW)->>'journal_id')::uuid,
        (to_jsonb(NEW)->>'id')::uuid
    );
    SELECT COUNT(*), COALESCE(SUM(amount), 0)
      INTO entry_count, entry_total
      FROM transfers_ledgerentry
     WHERE journal_id = checked_journal;
    IF entry_count <> 2 OR entry_total <> 0 THEN
        RAISE EXCEPTION 'ledger journal % must contain exactly two balanced entries', checked_journal;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER transfers_ledgerjournal_immutable
BEFORE UPDATE OR DELETE ON transfers_ledgerjournal
FOR EACH ROW EXECUTE FUNCTION transfers_reject_ledger_mutation();

CREATE TRIGGER transfers_ledgerentry_immutable
BEFORE UPDATE OR DELETE ON transfers_ledgerentry
FOR EACH ROW EXECUTE FUNCTION transfers_reject_ledger_mutation();

CREATE CONSTRAINT TRIGGER transfers_journal_balanced_from_journal
AFTER INSERT ON transfers_ledgerjournal
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION transfers_validate_balanced_journal();

CREATE CONSTRAINT TRIGGER transfers_journal_balanced_from_entry
AFTER INSERT ON transfers_ledgerentry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION transfers_validate_balanced_journal();
"""

LEDGER_TRIGGER_REVERSE_SQL = """
DROP TRIGGER IF EXISTS transfers_journal_balanced_from_entry ON transfers_ledgerentry;
DROP TRIGGER IF EXISTS transfers_journal_balanced_from_journal ON transfers_ledgerjournal;
DROP TRIGGER IF EXISTS transfers_ledgerentry_immutable ON transfers_ledgerentry;
DROP TRIGGER IF EXISTS transfers_ledgerjournal_immutable ON transfers_ledgerjournal;
DROP FUNCTION IF EXISTS transfers_validate_balanced_journal();
DROP FUNCTION IF EXISTS transfers_reject_ledger_mutation();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('USER', 'User'), ('SYSTEM_ISSUANCE', 'System issuance')], max_length=20)),
                ('code', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SEED_ISSUE', 'Seed issue'), ('TRANSFER', 'Transfer'), ('COMPENSATION', 'Compensation')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='transfers.ledgerjournal')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='transfers.ledgeraccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='transfers.ledgerjournal')),
            ],
        ),
        migrations.CreateModel(
            name='MockAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default='100000.00', max_digits=12)),
                ('is_open', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mock_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ledgerjournal',
            name='target_mock_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seed_journals', to='transfers.mockaccount'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='mock_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account', to='transfers.mockaccount'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='transfers.ledgerjournal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='transfers.mockaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='transfers.mockaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TransferAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transfers.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('canonical_payload', models.TextField()),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='transfers.mockaccount')),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_result', to='transfers.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='TransferSafetyState',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('BLOCKED', 'Blocked')], default='OPEN', max_length=8)),
                ('incident_id', models.UUIDField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='transfers_safety_singleton'), models.CheckConstraint(condition=models.Q(models.Q(('blocked_at__isnull', True), ('incident_id__isnull', True), ('state', 'OPEN')), models.Q(('blocked_at__isnull', False), ('incident_id__isnull', False), ('state', 'BLOCKED')), _connector='OR'), name='transfers_safety_state_consistent')],
            },
        ),
        migrations.AddConstraint(
            model_name='mockaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0), ('balance__lte', 1000000000)), name='transfers_balance_range'),
        ),
        migrations.AddConstraint(
            model_name='ledgerjournal',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SEED_ISSUE'), ('target_mock_account__isnull', False)), fields=('target_mock_account',), name='transfers_one_seed_per_account'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'USER'), ('mock_account__isnull', False)), models.Q(('kind', 'SYSTEM_ISSUANCE'), ('mock_account__isnull', True)), _connector='OR'), name='transfers_ledger_account_kind'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'idempotency_key'), name='transfers_sender_idempotency_unique'),
        ),
        migrations.RunPython(bootstrap_existing_accounts, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=LEDGER_TRIGGER_SQL,
            reverse_sql=LEDGER_TRIGGER_REVERSE_SQL,
            hints={"target_db": "default"},
        ),
    ]
