# Generated by Django 5.2.16 on 2026-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('account', 'Account'), ('ip', 'IP')], max_length=8)),
                ('identifier_digest', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'blocked_until'], name='accounts_login_block_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'identifier_digest'), name='accounts_login_throttle_identity_unique')],
            },
        ),
    ]
