# Generated by Django 5.2.16 on 2026-07-18 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginthrottle_accounts_login_updated_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevocationWorkerHeartbeat',
            fields=[
                ('worker_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('heartbeat_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='RevocationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('auth_epoch', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retry', 'Retry'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revocation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='accounts_revocation_ready_idx'), models.Index(fields=['status', 'lease_expires_at'], name='accounts_revocation_lease_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'auth_epoch'), name='accounts_revocation_user_epoch_unique'), models.CheckConstraint(condition=models.Q(('auth_epoch__gt', 0)), name='accounts_revocation_epoch_positive'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('heartbeat_at__isnull', False), ('lease_expires_at__isnull', False), ('status', 'processing')), models.Q(('completed_at__isnull', True), ('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True), ('status__in', ('pending', 'retry'))), models.Q(('completed_at__isnull', False), ('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True), ('status', 'completed')), _connector='OR'), name='accounts_revocation_status_state_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('heartbeat_at__isnull', True), ('lease_expires_at__isnull', True)), ('lease_expires_at__gte', models.F('heartbeat_at')), _connector='OR'), name='accounts_revocation_lease_after_heartbeat')],
            },
        ),
        migrations.CreateModel(
            name='UserSessionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('auth_epoch', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indexed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='accounts_session_user_rev_idx')],
            },
        ),
    ]
