# Generated by Django 5.2.16 on 2026-07-16 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='connection_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivery',
            field=models.CharField(choices=[('live', 'Live'), ('degraded', 'Degraded')], default='live', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='direct_user_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_rooms_as_high', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='direct_user_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_rooms_as_low', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'accepted_at'], name='chat_sender_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'connection_id', 'accepted_at'], name='chat_connection_rate_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'GLOBAL')), fields=('kind',), name='chat_single_global_room'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'DIRECT')), fields=('direct_user_low', 'direct_user_high'), name='chat_unique_direct_pair'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direct_user_high__isnull', True), ('direct_user_low__isnull', True), ('kind', 'GLOBAL')), models.Q(('direct_user_high__isnull', False), ('direct_user_low__isnull', False), ('direct_user_low__lt', models.F('direct_user_high')), ('kind', 'DIRECT')), _connector='OR'), name='chat_room_participant_shape'),
        ),
    ]
