# Generated by Django 5.2.16 on 2026-07-22 18:57

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_reject_product_image_legacy_key_alias'),
        ('chat', '0002_chatmessage_connection_id_chatmessage_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='room',
            name='chat_room_participant_shape',
        ),
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('DIRECT', 'Direct'), ('PRODUCT', 'Product')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direct_user_high__isnull', True), ('direct_user_low__isnull', True), ('kind__in', ('GLOBAL', 'PRODUCT'))), models.Q(('direct_user_high__isnull', False), ('direct_user_low__isnull', False), ('direct_user_low__lt', models.F('direct_user_high')), ('kind', 'DIRECT')), _connector='OR'), name='chat_room_participant_shape'),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_conversations_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_conversation', to='chat.room'),
        ),
        migrations.AddField(
            model_name='productconversation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_conversations_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='productconversation',
            constraint=models.UniqueConstraint(fields=('product', 'seller', 'buyer'), name='chat_unique_product_conversation'),
        ),
        migrations.AddConstraint(
            model_name='productconversation',
            constraint=models.CheckConstraint(condition=models.Q(('seller', models.F('buyer')), _negated=True), name='chat_product_parties_distinct'),
        ),
    ]
