# Generated by Django 5.2.16 on 2026-07-22 18:56

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_reject_product_image_legacy_key_alias'),
        ('moderation', '0002_abusereport_reason_and_more'),
        ('trades', '0002_review_reviewvisibilityaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('target_type', models.CharField(max_length=16)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField(max_length=500)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('result', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='AdminScopeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(choices=[('view_report', 'View report'), ('apply_sanction', 'Apply sanction'), ('release_sanction', 'Release sanction'), ('view_admin_audit', 'View admin audit'), ('hide_review', 'Hide review'), ('restore_review', 'Restore review')], max_length=32)),
                ('version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('granted_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'permissions': [('view_report', 'Can view scoped abuse reports'), ('apply_sanction', 'Can apply scoped sanctions'), ('release_sanction', 'Can release scoped sanctions'), ('view_admin_audit', 'Can view scoped administration audit'), ('hide_review', 'Can hide a reported scoped review'), ('restore_review', 'Can restore a reported scoped review'), ('manage_admin_scope', 'Can manage administration scopes')],
            },
        ),
        migrations.CreateModel(
            name='SanctionRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='abusereport',
            name='moderation_report_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='abusereport',
            name='moderation_report_context_matches_target',
        ),
        migrations.AddField(
            model_name='abusereport',
            name='target_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abuse_reports', to='trades.review'),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='context',
            field=models.CharField(choices=[('PROFILE', 'Profile'), ('PRODUCT', 'Product'), ('PRODUCT_INTERACTION', 'Product interaction'), ('GLOBAL_CHAT', 'Global chat'), ('DIRECT_CHAT', 'Direct chat'), ('REVIEW', 'Review')], max_length=24),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='target_type',
            field=models.CharField(choices=[('USER', 'User'), ('PRODUCT', 'Product'), ('REVIEW', 'Review')], max_length=12),
        ),
        migrations.AddIndex(
            model_name='abusereport',
            index=models.Index(fields=['target_type', 'target_review', 'consumed_by', '-created_at'], name='mod_report_review_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='abusereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_product__isnull', True), ('target_review__isnull', True), ('target_type', 'USER'), ('target_user__isnull', False)), models.Q(('target_product__isnull', False), ('target_review__isnull', True), ('target_type', 'PRODUCT'), ('target_user__isnull', True)), models.Q(('target_product__isnull', True), ('target_review__isnull', False), ('target_type', 'REVIEW'), ('target_user__isnull', True)), _connector='OR'), name='moderation_report_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='abusereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('context', 'PRODUCT'), ('target_type', 'PRODUCT')), models.Q(('context', 'REVIEW'), ('target_type', 'REVIEW')), models.Q(('target_type', 'USER'), models.Q(('context__in', ('PRODUCT', 'REVIEW')), _negated=True)), _connector='OR'), name='moderation_report_context_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='abusereport',
            constraint=models.UniqueConstraint(condition=models.Q(('target_review__isnull', False)), fields=('reporter', 'target_review'), name='moderation_unique_reporter_review'),
        ),
        migrations.AddField(
            model_name='adminaudit',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminscopegrant',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_scope_grants_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminscopegrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_scope_grants_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminscopegrant',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_scope_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminscopegrant',
            name='target_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_scope_grants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='adminscopegrant',
            name='target_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_scope_grants', to='trades.review'),
        ),
        migrations.AddField(
            model_name='adminscopegrant',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_scope_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanctionrelease',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release', to='moderation.moderationaction'),
        ),
        migrations.AddField(
            model_name='sanctionrelease',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='adminscopegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_product__isnull', True), ('target_review__isnull', True), ('target_user__isnull', False)), models.Q(('target_product__isnull', False), ('target_review__isnull', True), ('target_user__isnull', True)), models.Q(('target_product__isnull', True), ('target_review__isnull', False), ('target_user__isnull', True)), _connector='OR'), name='moderation_scope_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='adminscopegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('target_user__isnull', False)), fields=('staff', 'codename', 'target_user'), name='moderation_scope_active_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='adminscopegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('target_product__isnull', False)), fields=('staff', 'codename', 'target_product'), name='moderation_scope_active_product_unique'),
        ),
        migrations.AddConstraint(
            model_name='adminscopegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('target_review__isnull', False)), fields=('staff', 'codename', 'target_review'), name='moderation_scope_active_review_unique'),
        ),
    ]
